In [1]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense


Using TensorFlow backend.


In [2]:
model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape = (50, 50, 3), activation = 'relu'))

In [3]:
model.add(MaxPooling2D(pool_size = (2, 2)))
model.add(Conv2D(32, (3, 3), activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))

In [4]:
model.add(Flatten())

In [5]:
model.add(Dense(units = 128, activation = 'relu'))
model.add(Dense(units = 1, activation = 'sigmoid'))

In [6]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [7]:
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,shear_range = 0.2,zoom_range = 0.2,horizontal_flip = True)

In [8]:
url= r"C:\Users\aarushi.DESKTOP-EV4U7BF\Desktop\btech\Data Set\Cats and Dogs"

In [9]:
training_set = train_datagen.flow_from_directory(url,target_size = (50,50), batch_size = 32, class_mode = 'binary')

Found 25000 images belonging to 1 classes.


In [10]:
model.fit_generator(training_set,
                         steps_per_epoch = 100,
                         epochs = 25,
                         validation_steps = 2000)

Epoch 1/25
100/100 [==============================] - 21s 208ms/step - loss: 0.0081 - accuracy: 0.9931
Epoch 2/25
100/100 [==============================] - 20s 205ms/step - loss: 4.1303e-10 - accuracy: 1.0000
Epoch 3/25
100/100 [==============================] - 20s 198ms/step - loss: 6.8429e-09 - accuracy: 1.0000
Epoch 4/25
100/100 [==============================] - 21s 205ms/step - loss: 3.7192e-10 - accuracy: 1.0000
Epoch 5/25
100/100 [==============================] - 21s 205ms/step - loss: 1.1133e-10 - accuracy: 1.0000
Epoch 6/25
100/100 [==============================] - 21s 206ms/step - loss: 1.3270e-09 - accuracy: 1.0000
Epoch 7/25
100/100 [==============================] - 20s 199ms/step - loss: 4.9698e-11 - accuracy: 1.0000
Epoch 8/25
100/100 [==============================] - 20s 203ms/step - loss: 2.3141e-10 - accuracy: 1.0000
Epoch 9/25
100/100 [==============================] - 20s 197ms/step - loss: 2.2696e-10 - accuracy: 1.0000
Epoch 10/25
100/100 [====================

In [11]:
model_json = model.to_json()
with open("./model.json","w") as json_file:
  json_file.write(model_json)

In [12]:
model.save_weights("./model.h5")

print("Classifier trained Successfully!")

Classifier trained Successfully!


In [13]:
from keras.models import model_from_json

import numpy as np

In [14]:
import cv2

In [15]:
json_file = open('./model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

In [16]:
loaded_model.load_weights("./model.h5")
print("Loaded model from disk")

Loaded model from disk


In [17]:
print("Loaded model from disk")

Loaded model from disk


In [18]:
loaded_model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [33]:
img = cv2.imread(r"C:\Users\aarushi.DESKTOP-EV4U7BF\Desktop\btech\Data Set\test1\6.jpg")
print(img)


[[[134 155 187]
  [136 157 189]
  [138 159 191]
  ...
  [ 76  79 110]
  [ 58  61  92]
  [ 41  44  75]]

 [[139 160 192]
  [142 163 195]
  [146 167 199]
  ...
  [ 69  72 103]
  [ 53  56  87]
  [ 37  40  71]]

 [[144 165 197]
  [148 169 201]
  [152 173 205]
  ...
  [ 60  63  94]
  [ 45  48  79]
  [ 33  36  67]]

 ...

 [[ 80 101 183]
  [ 82 103 185]
  [ 82 103 185]
  ...
  [169 174 195]
  [169 174 195]
  [169 174 195]]

 [[ 79 100 182]
  [ 81 102 184]
  [ 82 103 185]
  ...
  [168 173 194]
  [166 171 192]
  [165 170 191]]

 [[ 79 100 182]
  [ 81 102 184]
  [ 82 103 185]
  ...
  [168 173 194]
  [165 170 191]
  [163 168 189]]]


In [34]:
img = cv2.resize(img, (50,50))
print(img.shape)
img = img.reshape(1, 50, 50, 3)

print(img.shape)

(50, 50, 3)
(1, 50, 50, 3)


In [37]:
result = loaded_model.predict_classes(img)
print()

if(result[0][0] == 1):
    print("Hey , Its a Dog")
else:
    print("Hey , Its a cat") 


Hey , Its a cat
